# Generated by Django 3.1.2 on 2020-11-02 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('fm', '0001_initial'), ('fm', '0002_auto_20201017_2021'), ('fm', '0003_remove_address_house_num'), ('fm', '0004_auto_20201023_1541'), ('fm', '0005_auto_20201023_1541'), ('fm', '0006_auto_20201023_1547'), ('fm', '0007_meal_status'), ('fm', '0008_meal_created_at')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='DietRestrictions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Diet Restrictions',
            },
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('l', 'Low'), ('h', 'High'), ('n', 'None')], default='n', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Food Preferences',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diet_restrictions', models.ManyToManyField(blank=True, to='fm.DietRestrictions')),
                ('food_preferences', models.ManyToManyField(blank=True, to='fm.FoodPreferences')),
                ('status', models.CharField(choices=[('ns', 'Not Started'), ('bp', 'Being Prepped'), ('ad', 'Almost Done'), ('fi', 'Finished'), ('er', 'En route')], default='ns', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.BinaryField(blank=True, editable=True, null=True)),
            ],
            options={
                'verbose_name': 'Cook',
            },
        ),
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('favorite_meal', models.UUIDField(blank=True, null=True)),
                ('address', models.ManyToManyField(blank=True, to='fm.Address')),
                ('diet_restrictions', models.ManyToManyField(blank=True, to='fm.DietRestrictions')),
                ('food_preferences', models.ManyToManyField(blank=True, to='fm.FoodPreferences')),
                ('meals', models.ManyToManyField(blank=True, to='fm.Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.BinaryField(blank=True, editable=True, null=True)),
            ],
            options={
                'verbose_name': 'Eater',
            },
        ),
    ]
